//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyProjet
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MyPFAEntities : DbContext
    {
        public MyPFAEntities()
            : base("name=MyPFAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Employe> Employe { get; set; }
        public virtual DbSet<Pointage> Pointage { get; set; }
        public virtual DbSet<Projets> Projets { get; set; }
        public virtual DbSet<Tache> Tache { get; set; }
    }
}
