//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyProjet
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tache
    {
        public int IdTache { get; set; }
        public string nomTache { get; set; }
        public string descTache { get; set; }
        public string type { get; set; }
        public string priorite { get; set; }
        public string status { get; set; }
        public Nullable<int> idProjet { get; set; }
        public Nullable<int> idEmp { get; set; }
        public Nullable<int> temp { get; set; }
        public string dateD { get; set; }
        public string dateF { get; set; }
        public Nullable<int> proggre { get; set; }
    
        public virtual Employe Employe { get; set; }
        public virtual Projets Projets { get; set; }
    }
}
